import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import * as path from 'path';
import { getProjectRoot, writeConstitution, readConstitution } from '../lib/filesystem.js';
import { getDate } from '../lib/utils.js';
import {
  MANDATORY_PRINCIPLES,
  buildConstitutionWithMandatoryPrinciples,
  validateConstitutionHasMandatoryPrinciples,
} from '../lib/constitution-enforcer.js';

export function registerConstitutionTool(server: McpServer): void {
  server.registerTool(
    'speckit_constitution',
    {
      description:
        'Create or update the project constitution — the governing principles that Claude (architect) and Copilot (developer) must follow. Mandatory principles (TDD-first, modular architecture, YAGNI, clarification-over-assumption) are ALWAYS included and cannot be removed. User-provided principles are added as project-specific principles.',
      inputSchema: {
        projectRoot: z.string().describe('Absolute path to the project root'),
        principles: z
          .array(
            z.object({
              name: z.string().describe('Short name/title for this principle'),
              description: z.string().describe('Full description of the principle'),
            })
          )
          .describe('List of PROJECT-SPECIFIC governing principles (mandatory principles are auto-included)'),
        governance: z
          .string()
          .optional()
          .describe('Optional governance rules (who approves specs, workflow gates, etc.)'),
      },
    },
    async ({ projectRoot, principles, governance }) => {
      const projectName = path.basename(projectRoot);
      const date = getDate();

      // Build mandatory principles section
      const mandatoryBlocks = MANDATORY_PRINCIPLES.map(
        (p) => `### ${p.name}\n${p.description}`
      ).join('\n\n');

      // Build project-specific principles section
      const projectPrincipleBlocks = principles
        .map(
          (p) => `### ${p.name}\n${p.description}`
        )
        .join('\n\n');

      const governanceSection = governance
        ? governance
        : 'All features must have a spec approved before implementation begins. Tests must pass before any implementation task is marked complete. The architect (Claude) manages specs; the developer (Copilot) implements them. When the developer encounters ANY ambiguity, they MUST stop and ask for human clarification — never assume.';

      const constitutionContent = `# ${projectName} Constitution

## Mandatory Principles (SpecKit Enforced)

> These principles are automatically enforced by the SpecKit MCP server.
> They cannot be removed or overridden by project-specific principles.

${mandatoryBlocks}

${principles.length > 0 ? `## Project-Specific Principles\n\n${projectPrincipleBlocks}\n\n` : ''}## Governance
${governanceSection}

**Version**: 1.0 | **Ratified**: ${date}
`;

      const filePath = await writeConstitution(constitutionContent);

      return {
        content: [
          {
            type: 'text' as const,
            text: `Constitution created/updated at: ${filePath}

---

${constitutionContent}

---

**${MANDATORY_PRINCIPLES.length} mandatory principles** (always enforced) + **${principles.length} project-specific principle(s)** recorded. This constitution will be embedded in all future \`copilot-instructions.md\` files generated by \`speckit_implement\`.

**Mandatory principles cannot be removed:**
${MANDATORY_PRINCIPLES.map((p) => `- ${p.name}`).join('\n')}`,
          },
        ],
      };
    }
  );
}
