import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import * as path from 'path';
import { getProjectRoot, writeConstitution, readConstitution } from '../lib/filesystem.js';
import { getDate } from '../lib/utils.js';

export function registerConstitutionTool(server: McpServer): void {
  server.registerTool(
    'speckit_constitution',
    {
      description:
        'Create or update the project constitution — the governing principles that Claude (architect) and Copilot (developer) must follow. The constitution is embedded in every copilot-instructions.md generation.',
      inputSchema: {
        projectRoot: z.string().describe('Absolute path to the project root'),
        principles: z
          .array(
            z.object({
              name: z.string().describe('Short name/title for this principle'),
              description: z.string().describe('Full description of the principle'),
            })
          )
          .describe('List of governing principles'),
        governance: z
          .string()
          .optional()
          .describe('Optional governance rules (who approves specs, workflow gates, etc.)'),
      },
    },
    async ({ projectRoot, principles, governance }) => {
      const projectName = path.basename(projectRoot);
      const date = getDate();

      const principleBlocks = principles
        .map(
          (p) => `### ${p.name}
${p.description}`
        )
        .join('\n\n');

      const governanceSection = governance
        ? governance
        : 'All features must have a spec approved before implementation begins. The architect (Claude) manages specs; the developer (Copilot) implements them.';

      const constitutionContent = `# ${projectName} Constitution

## Core Principles

${principleBlocks}

## Governance
${governanceSection}

**Version**: 1.0 | **Ratified**: ${date}
`;

      const filePath = await writeConstitution(constitutionContent);

      return {
        content: [
          {
            type: 'text' as const,
            text: `Constitution created/updated at: ${filePath}

---

${constitutionContent}

---

**${principles.length} principles** recorded. This constitution will be embedded in all future \`copilot-instructions.md\` files generated by \`speckit_implement\`.`,
          },
        ],
      };
    }
  );
}
