import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import * as path from 'path';
import {
  getProjectRoot,
  getSpecifyDir,
  getSpecsDir,
  ensureDir,
  writeFileAbsolute,
  fileExists,
} from '../lib/filesystem.js';
import { getTemplate } from '../lib/templates.js';
import { getDate } from '../lib/utils.js';
import { MANDATORY_PRINCIPLES, buildConstitutionWithMandatoryPrinciples } from '../lib/constitution-enforcer.js';

export function registerInitTool(server: McpServer): void {
  server.registerTool(
    'speckit_init',
    {
      description:
        'Initialize the .specify/ directory structure in the current project. Creates the spec management scaffold, copies templates, and prepares the project for Spec-Driven Development. The constitution is auto-populated with mandatory principles (TDD-first, modular architecture, YAGNI, clarification-over-assumption).',
      inputSchema: {
        projectName: z.string().describe('The name of the project'),
        principles: z
          .array(z.string())
          .optional()
          .describe('Optional additional project-specific guiding principles for the constitution (mandatory principles are always included)'),
      },
    },
    async ({ projectName, principles }) => {
      const projectRoot = getProjectRoot();
      const specifyDir = getSpecifyDir();
      const specsDir = getSpecsDir();
      const memoryDir = path.join(specifyDir, 'memory');
      const githubDir = path.join(projectRoot, '.github');

      const createdPaths: string[] = [];

      // Create directory structure
      ensureDir(specifyDir);
      ensureDir(specsDir);
      ensureDir(memoryDir);
      ensureDir(githubDir);
      createdPaths.push(specifyDir, specsDir, memoryDir);

      // Create .gitkeep in memory dir
      const gitkeepPath = path.join(memoryDir, '.gitkeep');
      if (!fileExists(gitkeepPath)) {
        await writeFileAbsolute(gitkeepPath, '');
        createdPaths.push(gitkeepPath);
      }

      // Create initial constitution with mandatory + optional principles
      const constitutionPath = path.join(memoryDir, 'constitution.md');
      if (!fileExists(constitutionPath)) {
        const projectPrinciples = principles ?? [];
        const constitutionContent = buildConstitutionWithMandatoryPrinciples(projectName, projectPrinciples);
        await writeFileAbsolute(constitutionPath, constitutionContent);
        createdPaths.push(constitutionPath);
      }

      // Create initial copilot-instructions.md stub
      const copilotPath = path.join(githubDir, 'copilot-instructions.md');
      if (!fileExists(copilotPath)) {
        const copilotStub = buildCopilotStub(projectName);
        await writeFileAbsolute(copilotPath, copilotStub);
        createdPaths.push(copilotPath);
      }

      // Create README in .specify/
      const specifyReadmePath = path.join(specifyDir, 'README.md');
      if (!fileExists(specifyReadmePath)) {
        const readmeContent = buildSpecifyReadme(projectName);
        await writeFileAbsolute(specifyReadmePath, readmeContent);
        createdPaths.push(specifyReadmePath);
      }

      return {
        content: [
          {
            type: 'text' as const,
            text: `SpecKit initialized for project: **${projectName}**

Project root: ${projectRoot}

**Created:**
${createdPaths.map((p) => `- ${path.relative(projectRoot, p)}`).join('\n')}

**Mandatory Principles (auto-enforced):**
${MANDATORY_PRINCIPLES.map((p) => `- **${p.name}**: ${p.shortDescription}`).join('\n')}

**Next steps:**
1. Edit \`.specify/memory/constitution.md\` to add project-specific principles (mandatory principles are already included and cannot be removed)
2. Run \`speckit_specify\` with a feature description to create your first spec
3. Follow up with \`speckit_plan\` → \`speckit_tasks\` → \`speckit_implement\`

The workflow: **init → constitution → specify → clarify → plan → tasks → implement → complete**`,
          },
        ],
      };
    }
  );
}

function buildCopilotStub(projectName: string): string {
  return `# Project: ${projectName}
# Architecture governed by Spec-Driven Development (SpecKit)

This file is auto-generated by the SpecKit MCP server.
It is updated automatically as features are planned and tasks are assigned.

## Mandatory Rules

### TDD-First
- Write tests BEFORE implementation code — always.
- No implementation task may begin until its corresponding test task is complete.

### Modular Architecture
- Every module/function has a single responsibility.
- Small, composable units with explicit interfaces.

### YAGNI
- Build only what the current spec requires. Nothing more.

### Clarification Over Assumption
- When in doubt, STOP and ASK. Never guess at requirements or behavior.
- If a decision is ambiguous, request explicit human input before proceeding.

## Current Status
No active feature. Run speckit_implement to populate this file with current task context.
`;
}

function buildSpecifyReadme(projectName: string): string {
  return `# ${projectName} Spec Directory

This directory is managed by SpecKit MCP (Spec-Driven Development).

## Structure

\`\`\`
.specify/
├── memory/
│   └── constitution.md    # Project governing principles (mandatory + project-specific)
└── specs/
    └── NNN-feature-name/
        ├── spec.md         # Feature specification
        ├── plan.md         # Implementation plan
        ├── tasks.md        # Task breakdown (tests BEFORE implementation)
        └── data-model.md   # Data model (optional)
\`\`\`

## Workflow

1. \`speckit_specify\` — Create a feature spec
2. \`speckit_clarify\` — Resolve ambiguities (MANDATORY before planning)
3. \`speckit_plan\` — Create technical plan
4. \`speckit_tasks\` — Break into tasks (tests generated first)
5. \`speckit_implement\` — Get next task for Copilot
6. \`speckit_complete_task\` — Mark task done

Do not edit spec files manually unless you know what you are doing.
`;
}
