import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import * as path from 'path';
import {
  getProjectRoot,
  getSpecifyDir,
  getSpecsDir,
  ensureDir,
  writeFileAbsolute,
  fileExists,
} from '../lib/filesystem.js';
import { getTemplate } from '../lib/templates.js';
import { getDate } from '../lib/utils.js';

export function registerInitTool(server: McpServer): void {
  server.registerTool(
    'speckit_init',
    {
      description:
        'Initialize the .specify/ directory structure in the current project. Creates the spec management scaffold, copies templates, and prepares the project for Spec-Driven Development.',
      inputSchema: {
        projectName: z.string().describe('The name of the project'),
        principles: z
          .array(z.string())
          .optional()
          .describe('Optional initial guiding principles for the project constitution'),
      },
    },
    async ({ projectName, principles }) => {
      const projectRoot = getProjectRoot();
      const specifyDir = getSpecifyDir();
      const specsDir = getSpecsDir();
      const memoryDir = path.join(specifyDir, 'memory');
      const githubDir = path.join(projectRoot, '.github');

      const createdPaths: string[] = [];

      // Create directory structure
      ensureDir(specifyDir);
      ensureDir(specsDir);
      ensureDir(memoryDir);
      ensureDir(githubDir);
      createdPaths.push(specifyDir, specsDir, memoryDir);

      // Create .gitkeep in memory dir
      const gitkeepPath = path.join(memoryDir, '.gitkeep');
      if (!fileExists(gitkeepPath)) {
        await writeFileAbsolute(gitkeepPath, '');
        createdPaths.push(gitkeepPath);
      }

      // Create initial constitution
      const constitutionPath = path.join(memoryDir, 'constitution.md');
      if (!fileExists(constitutionPath)) {
        const defaultPrinciples = principles ?? [
          'Write tests before or alongside implementation',
          'Keep functions small and single-purpose',
          'Prefer explicit over implicit',
        ];
        const constitutionContent = buildInitialConstitution(projectName, defaultPrinciples);
        await writeFileAbsolute(constitutionPath, constitutionContent);
        createdPaths.push(constitutionPath);
      }

      // Create initial copilot-instructions.md stub
      const copilotPath = path.join(githubDir, 'copilot-instructions.md');
      if (!fileExists(copilotPath)) {
        const copilotStub = buildCopilotStub(projectName);
        await writeFileAbsolute(copilotPath, copilotStub);
        createdPaths.push(copilotPath);
      }

      // Create README in .specify/
      const specifyReadmePath = path.join(specifyDir, 'README.md');
      if (!fileExists(specifyReadmePath)) {
        const readmeContent = buildSpecifyReadme(projectName);
        await writeFileAbsolute(specifyReadmePath, readmeContent);
        createdPaths.push(specifyReadmePath);
      }

      return {
        content: [
          {
            type: 'text' as const,
            text: `SpecKit initialized for project: **${projectName}**

Project root: ${projectRoot}

**Created:**
${createdPaths.map((p) => `- ${path.relative(projectRoot, p)}`).join('\n')}

**Next steps:**
1. Edit \`.specify/memory/constitution.md\` to define your project's governing principles
2. Run \`speckit_specify\` with a feature description to create your first spec
3. Follow up with \`speckit_plan\` → \`speckit_tasks\` → \`speckit_implement\`

The workflow: **init → constitution → specify → clarify → plan → tasks → implement → complete**`,
          },
        ],
      };
    }
  );
}

function buildInitialConstitution(projectName: string, principles: string[]): string {
  const date = getDate();
  const principleBlocks = principles
    .map((p, i) => {
      const name = p.split(' ').slice(0, 4).join(' ');
      return `### Principle ${i + 1}: ${name}\n${p}`;
    })
    .join('\n\n');

  return `# ${projectName} Constitution

## Core Principles

${principleBlocks}

## Governance
All features must have a spec approved before implementation begins. The architect (Claude) manages specs; the developer (Copilot) implements them.

**Version**: 1.0 | **Ratified**: ${date}
`;
}

function buildCopilotStub(projectName: string): string {
  return `# Project: ${projectName}
# Architecture governed by Spec-Driven Development (SpecKit)

This file is auto-generated by the SpecKit MCP server.
It is updated automatically as features are planned and tasks are assigned.

## Current Status
No active feature. Run speckit_implement to populate this file with current task context.
`;
}

function buildSpecifyReadme(projectName: string): string {
  return `# ${projectName} Spec Directory

This directory is managed by SpecKit MCP (Spec-Driven Development).

## Structure

\`\`\`
.specify/
├── memory/
│   └── constitution.md    # Project governing principles
└── specs/
    └── NNN-feature-name/
        ├── spec.md         # Feature specification
        ├── plan.md         # Implementation plan
        ├── tasks.md        # Task breakdown
        └── data-model.md   # Data model (optional)
\`\`\`

## Workflow

1. \`speckit_specify\` — Create a feature spec
2. \`speckit_clarify\` — Resolve ambiguities
3. \`speckit_plan\` — Create technical plan
4. \`speckit_tasks\` — Break into tasks
5. \`speckit_implement\` — Get next task for Copilot
6. \`speckit_complete_task\` — Mark task done

Do not edit spec files manually unless you know what you are doing.
`;
}
